anu:anu@itaas.dimensiondata.com
vanaja:vanaja@itaas.com
lakshmi205:lakshmi@itaas.com
gpathak:gpathak@itaas.com
kabali:kabali@itaas.com
rajinisir:rajini@itaas.com
varma:varma@itaas.com
kabalida:kabalida@itaas.com
thaliva:thaliva@itaas.com
enarciso:enarciso@itaas.com
vijayd:vijay@itaas.com
divya143:divya@itaas.com
yamini143:yamini@itaas.com
